### ISSUE TITLE
AOT failing to build after upgrading from 0.3.4 to 0.5.0

### ISSUE THREAD

**Issue by jeanpaulattard** [brandonroberts/angular-router-loader#59]
I've just upgraded my angular2-router-loader from  v0.3.4 to angular-router-loader v0.5.0, and as a result of the webpack build step when run for AOT is failing with the following error. _Note that the NGC step for AOT is passing successfully._

NB: For compliance issues I had to remove the proper path and module names with a placeholder. Hope this wouldn't be an issue

```
 52% building modules 553/790 modules 237 active ...@angular\core\src\profile\wtf_impl.jsModuleNotFoundError: Module not found: Error: Can't resolve '<somepath>\<modulename>.module.ngfactory' in '<project path>\src\app'
    at factoryCallback (<project path>\node_modules\webpack\lib\Compilation.js:259:39)
    at <project path>\node_modules\webpack\lib\NormalModuleFactory.js:234:19
    at onDoneResolving (<project path>\node_modules\webpack\lib\NormalModuleFactory.js:59:20)
    at <project path>\node_modules\webpack\lib\NormalModuleFactory.js:126:20
    at <project path>\node_modules\webpack\node_modules\async\dist\async.js:3694:9
    at <project path>\node_modules\webpack\node_modules\async\dist\async.js:356:16
    at iteratorCallback (<project path>\node_modules\webpack\node_modules\async\dist\async.js:934:13)
    at <project path>\node_modules\webpack\node_modules\async\dist\async.js:840:16
    at <project path>\node_modules\webpack\node_modules\async\dist\async.js:3691:13
    at apply (<project path>\node_modules\webpack\node_modules\async\dist\async.js:21:25)
    at <project path>\node_modules\webpack\node_modules\async\dist\async.js:56:12
    at <project path>\node_modules\webpack\lib\NormalModuleFactory.js:121:22
    at onResolved (<project path>\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:70:11)
    at loggingCallbackWrapper (<project path>\node_modules\webpack\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at afterInnerCallback (<project path>\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:138:10)
    at loggingCallbackWrapper (<project path>\node_modules\webpack\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at Resolver.applyPluginsAsyncSeriesBailResult1 (<project path>\node_modules\tapable\lib\Tapable.js:181:46)
    at innerCallback (<project path>\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:125:19)
    at loggingCallbackWrapper (<project path>\node_modules\webpack\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at <project path>\node_modules\tapable\lib\Tapable.js:283:15
    at <project path>\node_modules\webpack\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:38:4
    at loggingCallbackWrapper (<project path>\node_modules\webpack\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at afterInnerCallback (<project path>\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:138:10)
    at loggingCallbackWrapper (<project path>\node_modules\webpack\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at Resolver.applyPluginsAsyncSeriesBailResult1 (<project path>\node_modules\tapable\lib\Tapable.js:181:46)
    at innerCallback (<project path>\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:125:19)
    at loggingCallbackWrapper (<project path>\node_modules\webpack\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at <project path>\node_modules\tapable\lib\Tapable.js:283:15
    at innerCallback (<project path>\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:123:11)
    at loggingCallbackWrapper (<project path>\node_modules\webpack\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
resolve '<somepath>\<modulename>.module.ngfactory' in '<project path>\src\app'
  using description file: <project path>\package.json (relative path: ./src/app)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: <project path>\package.json (relative path: ./src/app)
    using description file: <project path>\package.json (relative path: <somepath>\<modulename>.module.ngfactory)
      as directory
        <project path>\<modulename>.module.ngfactory doesn't exist
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        <project path>\<modulename>.module.ngfactory doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        <project path>\<modulename>.module.ngfactory.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        <project path>\<modulename>.module.ngfactory.js doesn't exist
```

Specifically the  'Field 'browser' doesn't contain a valid alias configuration'

Current webpack version is : v2.2.1

I don't know if the source of the issue originates from the loader or from webpack itself.

**Comment by brandonroberts** [comment]
You will need to share some details about your build setup and how you are using the loader.

**Comment by jeanpaulattard** [comment]
Surely! :)

Here's the current loader configuration I'm using. https://gist.github.com/jeanpaulattard/289c9b967590e552b0cbf365a855d823

Should you require anything else let me know!

I'm currently first running the code through the ngc, with the following tsconfig :  https://gist.github.com/jeanpaulattard/6120ae1434c07b542fd920245cebcb44


Then the generated code is fed to webpack normally.

**Comment by brandonroberts** [comment]
Ok, just change your `genDir: 'compiled/src/app` in your angular-router-loader options to `genDir: 'compiled`

**Comment by jeanpaulattard** [comment]
Hi @brandonroberts 

Thank you very much for the solution! That fixed the issue I was having. :)

Sorry for not getting back to you promptly, I just got back to office and verified it.

Thanks again!
